name: resty
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <=4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  background_image: assets/images/gradient_background.png
  image: assets/images/Resty.png

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/resty-app-icon.png'
  web:
    generate: true
    image_path: 'assets/images/resty-app-icon.png'
  windows:
    generate: true
    image_path: 'assets/images/resty-app-icon.png'
  macos:
    generate: true
    image_path: 'assets/images/resty-app-icon.png'
